export const inKindContent = {
  es: {
    metaTitle: 'Nueva donación en especie | Edifica Digital',
    languageLabel: 'Cambiar idioma a inglés',
    languageCurrent: 'ES',
    languageAlternate: 'EN',
    backHome: 'Volver al inicio',
    eyebrow: 'Recepción de recursos',
    title: 'Nueva donación en especie',
    intro: 'Registra el origen, el traslado y cada producto. El borrador se guarda automáticamente en este dispositivo.',
    draftSaved: 'Borrador guardado',
    saveError: 'El navegador bloqueó el almacenamiento. Revisa los permisos del sitio e inténtalo otra vez.',
    requiredNote: 'Los campos marcados con * son obligatorios.',
    stepsLabel: 'Progreso del registro',
    steps: [
      { key: 'origin', short: 'Origen', label: 'Quién envía' },
      { key: 'shipment', short: 'Traslado', label: 'Cómo llega' },
      { key: 'items', short: 'Productos', label: 'Qué contiene' },
      { key: 'review', short: 'Revisión', label: 'Confirmar' },
    ],
    origin: {
      title: '¿Quién envía esta donación?',
      help: 'Usa el nombre que aparece en los documentos del embarque.',
      senderName: 'Nombre del remitente *',
      senderPlaceholder: 'Ej. Organización Aliada Alemania',
      senderType: 'Tipo de remitente',
      organization: 'Organización',
      individual: 'Persona',
      senderContact: 'Correo o teléfono',
      senderContactHint: 'Opcional · ayuda al equipo a confirmar datos',
      originCountry: 'País de origen *',
      originCountryPlaceholder: 'Ej. Alemania',
      originCity: 'Ciudad de origen',
      originCityPlaceholder: 'Ej. Hamburgo',
      destinationCountry: 'País de destino *',
      destinationCity: 'Ciudad de destino',
      destinationCityPlaceholder: 'Ej. La Guaira',
    },
    shipment: {
      title: '¿Cómo llegará la donación?',
      help: 'Completa los datos disponibles. Puedes actualizar la llegada cuando el embarque sea recibido.',
      transportMode: 'Medio de transporte *',
      modes: { sea: 'Marítimo', air: 'Aéreo', road: 'Terrestre', other: 'Otro' },
      containerNumber: 'Número del contenedor',
      containerPlaceholder: 'Ej. MSCU 123456 7',
      trackingNumber: 'Número de guía o seguimiento',
      trackingPlaceholder: 'Ej. DE/VE/2026-0817',
      departureDate: 'Fecha de salida',
      estimatedArrival: 'Llegada estimada *',
      actualArrival: 'Llegada real',
      status: 'Estado actual',
      statuses: {
        announced: 'Anunciado',
        in_transit: 'En tránsito',
        customs: 'En aduana',
        received: 'Recibido',
        closed: 'Cerrado',
      },
      notes: 'Notas del traslado',
      notesPlaceholder: 'Puerto, agente aduanal u otra información útil',
    },
    items: {
      title: '¿Qué contiene el embarque?',
      help: 'Registra cada grupo de productos por separado. Así será más fácil verificar, almacenar y entregar.',
      item: 'Producto',
      description: 'Nombre o descripción *',
      descriptionPlaceholder: 'Ej. Pasta libre de gluten',
      category: 'Categoría *',
      categories: {
        food: 'Alimentos',
        clothing: 'Ropa',
        hygiene: 'Higiene',
        medical: 'Salud',
        household: 'Hogar',
        other: 'Otro',
      },
      quantity: 'Cantidad declarada *',
      unit: 'Unidad *',
      units: {
        unit: 'Unidades',
        kilogram: 'Kilogramos',
        liter: 'Litros',
        box: 'Cajas',
        pallet: 'Paletas',
        bag: 'Sacos',
      },
      value: 'Valor de referencia',
      valueHint: 'Opcional · valor informativo de los bienes',
      currency: 'Moneda',
      foodDetails: 'Datos del alimento',
      glutenFree: 'Libre de gluten',
      lotCode: 'Código de lote',
      expiryDate: 'Fecha de vencimiento',
      allergens: 'Alérgenos o advertencias',
      allergensPlaceholder: 'Ej. Puede contener soya',
      extraDetails: 'Agregar detalles',
      notes: 'Notas del producto',
      notesPlaceholder: 'Marca, condición, talla u otra información',
      remove: 'Eliminar producto',
      add: 'Agregar otro producto',
      count: (count) => `${count} ${count === 1 ? 'producto' : 'productos'}`,
    },
    review: {
      title: 'Revisa antes de guardar',
      help: 'Confirma que los datos coinciden con los documentos disponibles.',
      origin: 'Origen y remitente',
      route: 'Ruta y traslado',
      goods: 'Contenido declarado',
      sender: 'Remitente',
      routeLabel: 'Ruta',
      eta: 'Llegada estimada',
      transport: 'Transporte',
      container: 'Contenedor',
      quantity: 'Cantidad',
      referenceValue: 'Valor de referencia',
      dietary: 'Atributos',
      glutenFree: 'Libre de gluten',
      edit: 'Editar',
      confirmation: 'Confirmo que revisé la información disponible.',
      missingTitle: 'Completa estos pasos para guardar:',
    },
    actions: {
      back: 'Atrás',
      continue: 'Continuar',
      review: 'Revisar registro',
      save: 'Guardar donación',
      saving: 'Guardando…',
      startAnother: 'Registrar otra donación',
      home: 'Ir al inicio',
    },
    success: {
      eyebrow: 'Registro preparado',
      title: 'La donación quedó registrada en este dispositivo.',
      copy: 'El equipo puede usar esta referencia para continuar la verificación y la recepción del embarque.',
      reference: 'Referencia del embarque',
      note: 'La sincronización con Supabase se activará al conectar el entorno operativo.',
    },
  },
  en: {
    metaTitle: 'New in-kind donation | Edifica Digital',
    languageLabel: 'Cambiar idioma a español',
    languageCurrent: 'EN',
    languageAlternate: 'ES',
    backHome: 'Back to home',
    eyebrow: 'Resource intake',
    title: 'New in-kind donation',
    intro: 'Record the origin, transport, and each item. The draft is saved automatically on this device.',
    draftSaved: 'Draft saved',
    saveError: 'The browser blocked storage. Check this site’s permissions and try again.',
    requiredNote: 'Fields marked with * are required.',
    stepsLabel: 'Registration progress',
    steps: [
      { key: 'origin', short: 'Origin', label: 'Who sends it' },
      { key: 'shipment', short: 'Transport', label: 'How it arrives' },
      { key: 'items', short: 'Goods', label: 'What it contains' },
      { key: 'review', short: 'Review', label: 'Confirm' },
    ],
    origin: {
      title: 'Who is sending this donation?',
      help: 'Use the name shown on the shipment documents.',
      senderName: 'Sender name *',
      senderPlaceholder: 'E.g. Partner Organization Germany',
      senderType: 'Sender type',
      organization: 'Organization',
      individual: 'Individual',
      senderContact: 'Email or phone',
      senderContactHint: 'Optional · helps the team confirm details',
      originCountry: 'Origin country *',
      originCountryPlaceholder: 'E.g. Germany',
      originCity: 'Origin city',
      originCityPlaceholder: 'E.g. Hamburg',
      destinationCountry: 'Destination country *',
      destinationCity: 'Destination city',
      destinationCityPlaceholder: 'E.g. La Guaira',
    },
    shipment: {
      title: 'How will the donation arrive?',
      help: 'Complete the details available today. Arrival can be updated when the shipment is received.',
      transportMode: 'Transport mode *',
      modes: { sea: 'Sea', air: 'Air', road: 'Road', other: 'Other' },
      containerNumber: 'Container number',
      containerPlaceholder: 'E.g. MSCU 123456 7',
      trackingNumber: 'Tracking or waybill number',
      trackingPlaceholder: 'E.g. DE/VE/2026-0817',
      departureDate: 'Departure date',
      estimatedArrival: 'Estimated arrival *',
      actualArrival: 'Actual arrival',
      status: 'Current status',
      statuses: {
        announced: 'Announced',
        in_transit: 'In transit',
        customs: 'At customs',
        received: 'Received',
        closed: 'Closed',
      },
      notes: 'Transport notes',
      notesPlaceholder: 'Port, customs agent, or other useful information',
    },
    items: {
      title: 'What is inside the shipment?',
      help: 'Record each group of goods separately. This supports clear verification, storage, and delivery.',
      item: 'Item',
      description: 'Name or description *',
      descriptionPlaceholder: 'E.g. Gluten-free pasta',
      category: 'Category *',
      categories: {
        food: 'Food',
        clothing: 'Clothing',
        hygiene: 'Hygiene',
        medical: 'Health',
        household: 'Household',
        other: 'Other',
      },
      quantity: 'Declared quantity *',
      unit: 'Unit *',
      units: {
        unit: 'Units',
        kilogram: 'Kilograms',
        liter: 'Liters',
        box: 'Boxes',
        pallet: 'Pallets',
        bag: 'Bags',
      },
      value: 'Reference value',
      valueHint: 'Optional · informative value of the goods',
      currency: 'Currency',
      foodDetails: 'Food details',
      glutenFree: 'Gluten-free',
      lotCode: 'Lot code',
      expiryDate: 'Expiry date',
      allergens: 'Allergens or warnings',
      allergensPlaceholder: 'E.g. May contain soy',
      extraDetails: 'Add details',
      notes: 'Item notes',
      notesPlaceholder: 'Brand, condition, size, or other information',
      remove: 'Remove item',
      add: 'Add another item',
      count: (count) => `${count} ${count === 1 ? 'item' : 'items'}`,
    },
    review: {
      title: 'Review before saving',
      help: 'Confirm that the details match the available documents.',
      origin: 'Origin and sender',
      route: 'Route and transport',
      goods: 'Declared contents',
      sender: 'Sender',
      routeLabel: 'Route',
      eta: 'Estimated arrival',
      transport: 'Transport',
      container: 'Container',
      quantity: 'Quantity',
      referenceValue: 'Reference value',
      dietary: 'Attributes',
      glutenFree: 'Gluten-free',
      edit: 'Edit',
      confirmation: 'I confirm that I reviewed the available information.',
      missingTitle: 'Complete these steps before saving:',
    },
    actions: {
      back: 'Back',
      continue: 'Continue',
      review: 'Review record',
      save: 'Save donation',
      saving: 'Saving…',
      startAnother: 'Record another donation',
      home: 'Go to home',
    },
    success: {
      eyebrow: 'Record prepared',
      title: 'The donation was recorded on this device.',
      copy: 'The team can use this reference to continue shipment verification and receipt.',
      reference: 'Shipment reference',
      note: 'Supabase synchronization will activate when the operational environment is connected.',
    },
  },
}
