export const inKindContent = {
  es: {
    metaTitle: 'Nueva donación en especie | Edifica Digital',
    languageLabel: 'Cambiar idioma a inglés',
    languageCurrent: 'ES',
    languageAlternate: 'EN',
    backHome: 'Volver al inicio',
    eyebrow: 'Recepción de recursos',
    title: 'Nueva donación en especie',
    intro: 'Registra el origen, el traslado y cada producto. El borrador se guarda automáticamente en este dispositivo.',
    draftSaved: 'Borrador guardado',
    saveError: 'El navegador bloqueó el almacenamiento. Revisa los permisos del sitio e inténtalo otra vez.',
    submissionErrors: {
      authentication: 'La sesión necesita renovarse. Ingresa nuevamente con tu correo.',
      evidence_validation: 'Revisa los archivos seleccionados y conserva los formatos y tamaños permitidos.',
      evidence_upload: 'La evidencia sigue disponible en esta pantalla. Intenta guardar otra vez.',
      record: 'El borrador y la evidencia siguen disponibles. Intenta guardar otra vez.',
      default: 'El registro sigue disponible como borrador. Intenta guardar otra vez.',
    },
    requiredNote: 'Los campos marcados con * son obligatorios.',
    stepsLabel: 'Progreso del registro',
    steps: [
      { key: 'origin', short: 'Origen', label: 'Quién envía' },
      { key: 'shipment', short: 'Traslado', label: 'Cómo llega' },
      { key: 'items', short: 'Productos', label: 'Qué contiene' },
      { key: 'review', short: 'Revisión', label: 'Confirmar' },
    ],
    origin: {
      title: '¿Quién envía esta donación?',
      help: 'Usa el nombre que aparece en los documentos del embarque.',
      senderName: 'Nombre del remitente *',
      senderPlaceholder: 'Ej. Organización Aliada Alemania',
      senderType: 'Tipo de remitente',
      organization: 'Organización',
      individual: 'Persona',
      senderContact: 'Correo o teléfono',
      senderContactHint: 'Opcional · ayuda al equipo a confirmar datos',
      originCountry: 'País de origen *',
      originCountryPlaceholder: 'Ej. Alemania',
      originCity: 'Ciudad de origen',
      originCityPlaceholder: 'Ej. Hamburgo',
      destinationCountry: 'País de destino *',
      destinationCity: 'Ciudad de destino',
      destinationCityPlaceholder: 'Ej. La Guaira',
    },
    shipment: {
      title: '¿Cómo llegará la donación?',
      help: 'Completa los datos disponibles. Puedes actualizar la llegada cuando el embarque sea recibido.',
      transportMode: 'Medio de transporte *',
      modes: { sea: 'Marítimo', air: 'Aéreo', road: 'Terrestre', other: 'Otro' },
      containerNumber: 'Número del contenedor',
      containerPlaceholder: 'Ej. MSCU 123456 7',
      trackingNumber: 'Número de guía o seguimiento',
      trackingPlaceholder: 'Ej. DE/VE/2026-0817',
      departureDate: 'Fecha de salida',
      estimatedArrival: 'Llegada estimada *',
      actualArrival: 'Llegada real',
      status: 'Estado actual',
      statuses: {
        announced: 'Anunciado',
        in_transit: 'En tránsito',
        customs: 'En aduana',
        received: 'Recibido',
        closed: 'Cerrado',
      },
      notes: 'Notas del traslado',
      notesPlaceholder: 'Puerto, agente aduanal u otra información útil',
    },
    items: {
      title: '¿Qué contiene el embarque?',
      help: 'Registra cada grupo de productos por separado. Así será más fácil verificar, almacenar y entregar.',
      item: 'Producto',
      description: 'Nombre o descripción *',
      descriptionPlaceholder: 'Ej. Pasta libre de gluten',
      category: 'Categoría *',
      categories: {
        food: 'Alimentos',
        clothing: 'Ropa',
        hygiene: 'Higiene',
        medical: 'Salud',
        household: 'Hogar',
        other: 'Otro',
      },
      quantity: 'Cantidad declarada *',
      unit: 'Unidad *',
      units: {
        unit: 'Unidades',
        kilogram: 'Kilogramos',
        liter: 'Litros',
        box: 'Cajas',
        pallet: 'Paletas',
        bag: 'Sacos',
      },
      value: 'Valor de referencia',
      valueHint: 'Opcional · valor informativo de los bienes',
      currency: 'Moneda',
      foodDetails: 'Datos del alimento',
      glutenFree: 'Libre de gluten',
      lotCode: 'Código de lote',
      expiryDate: 'Fecha de vencimiento',
      allergens: 'Alérgenos o advertencias',
      allergensPlaceholder: 'Ej. Puede contener soya',
      extraDetails: 'Agregar detalles',
      notes: 'Notas del producto',
      notesPlaceholder: 'Marca, condición, talla u otra información',
      remove: 'Eliminar producto',
      add: 'Agregar otro producto',
      count: (count) => `${count} ${count === 1 ? 'producto' : 'productos'}`,
    },
    review: {
      title: 'Revisa antes de guardar',
      help: 'Confirma que los datos coinciden con los documentos disponibles.',
      origin: 'Origen y remitente',
      route: 'Ruta y traslado',
      goods: 'Contenido declarado',
      sender: 'Remitente',
      routeLabel: 'Ruta',
      eta: 'Llegada estimada',
      transport: 'Transporte',
      container: 'Contenedor',
      quantity: 'Cantidad',
      referenceValue: 'Valor de referencia',
      dietary: 'Atributos',
      glutenFree: 'Libre de gluten',
      edit: 'Editar',
      confirmation: 'Confirmo que revisé la información disponible.',
      missingTitle: 'Completa estos pasos para guardar:',
      evidence: 'Evidencias del embarque',
      evidenceHelp: 'Agrega listas de empaque, documentos de transporte, aduana, inspección, recepción o fotografías.',
      evidenceFormats: 'PDF, JPG, PNG o WebP · hasta 20 MB por archivo',
      evidenceAdd: 'Agregar evidencias',
      evidenceType: 'Tipo de evidencia',
      evidenceTypes: {
        packing_list: 'Lista de empaque',
        bill_of_lading: 'Documento de transporte',
        customs: 'Documento aduanal',
        inspection: 'Inspección',
        receipt: 'Acta de recepción',
        photo: 'Fotografía',
        other: 'Otro documento',
      },
      evidenceRemove: 'Quitar',
      evidenceUnsupported: 'Usa un archivo PDF, JPG, PNG o WebP.',
      evidenceTooLarge: 'El archivo supera 20 MB.',
      evidenceSession: 'Los archivos permanecen seleccionados mientras esta pantalla siga abierta.',
    },
    actions: {
      back: 'Atrás',
      continue: 'Continuar',
      review: 'Revisar registro',
      save: 'Guardar donación',
      saving: 'Guardando…',
      startAnother: 'Registrar otra donación',
      home: 'Ir al inicio',
    },
    success: {
      eyebrow: 'Registro confirmado',
      title: 'La donación quedó guardada en la plataforma.',
      copy: 'La referencia confirma el registro del remitente, el embarque, los productos y sus evidencias.',
      reference: 'Referencia del embarque',
      note: 'El borrador local fue cerrado después de recibir la confirmación de Supabase.',
    },
    auth: {
      eyebrow: 'Acceso operativo',
      title: 'Ingresa con tu correo autorizado',
      body: 'Recibirás un enlace seguro para abrir el registro de donaciones.',
      email: 'Correo del equipo',
      emailPlaceholder: 'nombre@organizacion.org',
      sendLink: 'Enviar enlace de acceso',
      sending: 'Enviando…',
      requestError: 'Revisa el correo e intenta solicitar el enlace otra vez.',
      linkEyebrow: 'Enlace enviado',
      linkTitle: 'Revisa tu correo',
      linkBody: 'Abre el enlace desde este dispositivo para continuar con el registro.',
      sendAgain: 'Enviar otro enlace',
      restrictedEyebrow: 'Acceso pendiente',
      restrictedTitle: 'Esta cuenta requiere autorización operativa',
      restrictedBody: 'El equipo responsable puede activar esta cuenta en la lista de operadores.',
      signOut: 'Usar otra cuenta',
      errorEyebrow: 'Sesión pendiente',
      errorTitle: 'Renueva el acceso',
      errorBody: 'Cierra esta sesión y solicita un enlace nuevo.',
      configurationEyebrow: 'Configuración pendiente',
      configurationTitle: 'Conecta el entorno operativo',
      configurationBody: 'Agrega la URL y la clave publicable de Supabase a las variables del proyecto.',
    },
  },
  en: {
    metaTitle: 'New in-kind donation | Edifica Digital',
    languageLabel: 'Cambiar idioma a español',
    languageCurrent: 'EN',
    languageAlternate: 'ES',
    backHome: 'Back to home',
    eyebrow: 'Resource intake',
    title: 'New in-kind donation',
    intro: 'Record the origin, transport, and each item. The draft is saved automatically on this device.',
    draftSaved: 'Draft saved',
    saveError: 'The browser blocked storage. Check this site’s permissions and try again.',
    submissionErrors: {
      authentication: 'Refresh the session by signing in with your email again.',
      evidence_validation: 'Review the selected files and keep the approved formats and sizes.',
      evidence_upload: 'The evidence remains available on this screen. Try saving again.',
      record: 'The draft and evidence remain available. Try saving again.',
      default: 'The record remains available as a draft. Try saving again.',
    },
    requiredNote: 'Fields marked with * are required.',
    stepsLabel: 'Registration progress',
    steps: [
      { key: 'origin', short: 'Origin', label: 'Who sends it' },
      { key: 'shipment', short: 'Transport', label: 'How it arrives' },
      { key: 'items', short: 'Goods', label: 'What it contains' },
      { key: 'review', short: 'Review', label: 'Confirm' },
    ],
    origin: {
      title: 'Who is sending this donation?',
      help: 'Use the name shown on the shipment documents.',
      senderName: 'Sender name *',
      senderPlaceholder: 'E.g. Partner Organization Germany',
      senderType: 'Sender type',
      organization: 'Organization',
      individual: 'Individual',
      senderContact: 'Email or phone',
      senderContactHint: 'Optional · helps the team confirm details',
      originCountry: 'Origin country *',
      originCountryPlaceholder: 'E.g. Germany',
      originCity: 'Origin city',
      originCityPlaceholder: 'E.g. Hamburg',
      destinationCountry: 'Destination country *',
      destinationCity: 'Destination city',
      destinationCityPlaceholder: 'E.g. La Guaira',
    },
    shipment: {
      title: 'How will the donation arrive?',
      help: 'Complete the details available today. Arrival can be updated when the shipment is received.',
      transportMode: 'Transport mode *',
      modes: { sea: 'Sea', air: 'Air', road: 'Road', other: 'Other' },
      containerNumber: 'Container number',
      containerPlaceholder: 'E.g. MSCU 123456 7',
      trackingNumber: 'Tracking or waybill number',
      trackingPlaceholder: 'E.g. DE/VE/2026-0817',
      departureDate: 'Departure date',
      estimatedArrival: 'Estimated arrival *',
      actualArrival: 'Actual arrival',
      status: 'Current status',
      statuses: {
        announced: 'Announced',
        in_transit: 'In transit',
        customs: 'At customs',
        received: 'Received',
        closed: 'Closed',
      },
      notes: 'Transport notes',
      notesPlaceholder: 'Port, customs agent, or other useful information',
    },
    items: {
      title: 'What is inside the shipment?',
      help: 'Record each group of goods separately. This supports clear verification, storage, and delivery.',
      item: 'Item',
      description: 'Name or description *',
      descriptionPlaceholder: 'E.g. Gluten-free pasta',
      category: 'Category *',
      categories: {
        food: 'Food',
        clothing: 'Clothing',
        hygiene: 'Hygiene',
        medical: 'Health',
        household: 'Household',
        other: 'Other',
      },
      quantity: 'Declared quantity *',
      unit: 'Unit *',
      units: {
        unit: 'Units',
        kilogram: 'Kilograms',
        liter: 'Liters',
        box: 'Boxes',
        pallet: 'Pallets',
        bag: 'Bags',
      },
      value: 'Reference value',
      valueHint: 'Optional · informative value of the goods',
      currency: 'Currency',
      foodDetails: 'Food details',
      glutenFree: 'Gluten-free',
      lotCode: 'Lot code',
      expiryDate: 'Expiry date',
      allergens: 'Allergens or warnings',
      allergensPlaceholder: 'E.g. May contain soy',
      extraDetails: 'Add details',
      notes: 'Item notes',
      notesPlaceholder: 'Brand, condition, size, or other information',
      remove: 'Remove item',
      add: 'Add another item',
      count: (count) => `${count} ${count === 1 ? 'item' : 'items'}`,
    },
    review: {
      title: 'Review before saving',
      help: 'Confirm that the details match the available documents.',
      origin: 'Origin and sender',
      route: 'Route and transport',
      goods: 'Declared contents',
      sender: 'Sender',
      routeLabel: 'Route',
      eta: 'Estimated arrival',
      transport: 'Transport',
      container: 'Container',
      quantity: 'Quantity',
      referenceValue: 'Reference value',
      dietary: 'Attributes',
      glutenFree: 'Gluten-free',
      edit: 'Edit',
      confirmation: 'I confirm that I reviewed the available information.',
      missingTitle: 'Complete these steps before saving:',
      evidence: 'Shipment evidence',
      evidenceHelp: 'Add packing lists, transport, customs, inspection, receipt, or photographic evidence.',
      evidenceFormats: 'PDF, JPG, PNG, or WebP · up to 20 MB per file',
      evidenceAdd: 'Add evidence',
      evidenceType: 'Evidence type',
      evidenceTypes: {
        packing_list: 'Packing list',
        bill_of_lading: 'Transport document',
        customs: 'Customs document',
        inspection: 'Inspection',
        receipt: 'Receipt record',
        photo: 'Photograph',
        other: 'Other document',
      },
      evidenceRemove: 'Remove',
      evidenceUnsupported: 'Use a PDF, JPG, PNG, or WebP file.',
      evidenceTooLarge: 'The file is larger than 20 MB.',
      evidenceSession: 'Files remain selected while this screen stays open.',
    },
    actions: {
      back: 'Back',
      continue: 'Continue',
      review: 'Review record',
      save: 'Save donation',
      saving: 'Saving…',
      startAnother: 'Record another donation',
      home: 'Go to home',
    },
    success: {
      eyebrow: 'Record confirmed',
      title: 'The donation was saved to the platform.',
      copy: 'The reference confirms the sender, shipment, goods, and evidence records.',
      reference: 'Shipment reference',
      note: 'The local draft closed after Supabase confirmed persistence.',
    },
    auth: {
      eyebrow: 'Operational access',
      title: 'Sign in with your authorized email',
      body: 'You will receive a secure link to open donation intake.',
      email: 'Team email',
      emailPlaceholder: 'name@organization.org',
      sendLink: 'Send access link',
      sending: 'Sending…',
      requestError: 'Review the email and request the link again.',
      linkEyebrow: 'Link sent',
      linkTitle: 'Check your email',
      linkBody: 'Open the link on this device to continue the record.',
      sendAgain: 'Send another link',
      restrictedEyebrow: 'Access pending',
      restrictedTitle: 'This account requires operational authorization',
      restrictedBody: 'The responsible team can activate this account in the operator list.',
      signOut: 'Use another account',
      errorEyebrow: 'Session pending',
      errorTitle: 'Refresh access',
      errorBody: 'Close this session and request a new link.',
      configurationEyebrow: 'Configuration pending',
      configurationTitle: 'Connect the operational environment',
      configurationBody: 'Add the Supabase URL and publishable key to the project variables.',
    },
  },
}
