import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase.js'
import { OperatorAccessScreen } from '../in-kind/OperatorAccess.jsx'
import { useOperatorAccess } from '../in-kind/useOperatorAccess.js'
import ManagementStandaloneShell from './ManagementStandaloneShell.jsx'
import './management-reports-v2.css'
import './management-reports-unified.css'
import './management-reports-cycles.css'

const statusLabels = {
  es: { draft: 'Borrador', submitted: 'Enviado a DIAF', reviewed: 'Revisado por DIAF', approved: 'Aprobado por DIAF', closed: 'Cerrado', none: 'Pendiente' },
  en: { draft: 'Draft', submitted: 'Sent to Finance', reviewed: 'Reviewed by Finance', approved: 'Approved by Finance', closed: 'Closed', none: 'Pending' },
}
const kindLabels = {
  es: { result: 'Resultado', output: 'Producto', process: 'Proceso', impact: 'Impacto' },
  en: { result: 'Outcome', output: 'Output', process: 'Process', impact: 'Impact' },
}
const copy = {
  es: {
    eyebrow: 'INFORMES DE GESTIÓN', title: 'Informes por corte y cierre anual', intro: 'Cada Dirección redacta su informe, vincula cada declaración al objetivo o indicador correspondiente y Edifica incorpora automáticamente las cifras oficiales de Seguimiento.',
    organization: 'Organización', year: 'Año de trabajo', window: 'Informe / corte', units: 'Direcciones', started: 'Iniciados', submitted: 'Enviados a DIAF', approved: 'Aprobados por DIAF',
    directory: 'INFORMES POR DIRECCIÓN', directoryTitle: 'Estado de los informes', directoryHelp: 'Selecciona el corte y abre la Dirección. Crear informe permite redactar manualmente los statements; los números de los indicadores se arrastran automáticamente.',
    pending: 'Sin informe iniciado', updated: 'Actualizado', create: 'Crear informe', edit: 'Editar informe', view: 'Ver', review: 'Revisar', consolidated: 'Ver consolidado', back: 'Volver', print: 'Imprimir / PDF',
    report: 'INFORME DE LA DIRECCIÓN', executive: 'Resumen ejecutivo', executiveHelp: 'Síntesis del corte. Puedes redactarla libremente.',
    statements: 'Declaraciones del informe', statementsHelp: 'Escribe cada hecho relevante por separado. Ej.: “Se efectuaron las cuatro vigilias nacionales de oración”. Vincúlalo al objetivo y, cuando corresponda, al indicador.', addStatement: '＋ Agregar declaración', statement: 'Declaración / statement', objective: 'Objetivo', indicator: 'Indicador (opcional)', selectObjective: 'Seleccionar objetivo', selectIndicator: 'Sin indicador específico',
    indicators: 'Indicadores del corte', indicatorsHelp: 'Estas cifras vienen de Seguimiento dentro de las fechas de este corte. No se vuelven a escribir en el informe.', target: 'Meta', achieved: 'Logrado', execution: 'Ejecución', noIndicators: 'Esta Dirección todavía no tiene indicadores para el año seleccionado.',
    scheduled: 'Actividades del Plan Anual en este corte', scheduledHelp: 'Referencia automática del calendario de la Dirección. Sirve para recordar qué estaba planificado durante el período.', noScheduled: 'No hay actividades calendarizadas dentro de este corte.',
    challenges: 'Retos o asuntos pendientes', next: 'Próximos pasos', addChallenge: '＋ Agregar reto', addNext: '＋ Agregar próximo paso', reviewer: 'Observaciones de DIAF',
    saveDraft: 'Guardar borrador', send: 'Enviar informe a DIAF', reviewed: 'Marcar revisado', approve: 'Aprobar informe', saving: 'Guardando…', saved: 'Informe actualizado.', close: 'Cerrar', remove: 'Eliminar',
    destination: 'Rendición final', flow: 'La Dirección prepara y envía. DIAF recibe, revisa y aprueba.', noObjectives: 'Esta Dirección todavía no tiene objetivos en el Plan Anual. Crea los objetivos antes de completar el informe.', linkPlan: 'Abrir Plan Anual', missingLink: 'Cada declaración debe estar vinculada por lo menos a un objetivo.',
    windowRange: 'Período informado', annual: 'Informe anual', periodic: 'Corte de Junta Ejecutiva', reviewerOnly: 'Modo revisión DIAF: el contenido de la Dirección queda en solo lectura y puedes agregar observaciones o aprobar.', consolidatedTitle: 'CONSOLIDADO INSTITUCIONAL', managementByUnit: 'Informes por Dirección', loading: 'Cargando informes…', noItems: 'Sin información registrada.',
  },
  en: {
    eyebrow: 'MANAGEMENT REPORTS', title: 'Periodic and annual reports', intro: 'Each unit writes its report, links every statement to the relevant objective or indicator, and Edifica automatically includes official Tracking figures.',
    organization: 'Organization', year: 'Work year', window: 'Report / window', units: 'Units', started: 'Started', submitted: 'Sent to Finance', approved: 'Approved by Finance',
    directory: 'REPORTS BY UNIT', directoryTitle: 'Report status', directoryHelp: 'Select the reporting window and open the unit. Create report allows manual statements while indicator figures are pulled automatically.',
    pending: 'No report started', updated: 'Updated', create: 'Create report', edit: 'Edit report', view: 'View', review: 'Review', consolidated: 'View consolidated', back: 'Back', print: 'Print / PDF',
    report: 'UNIT REPORT', executive: 'Executive summary', executiveHelp: 'Free-form summary of the reporting window.',
    statements: 'Report statements', statementsHelp: 'Write each relevant fact separately and link it to the objective and, when applicable, the indicator.', addStatement: '＋ Add statement', statement: 'Statement', objective: 'Objective', indicator: 'Indicator (optional)', selectObjective: 'Select objective', selectIndicator: 'No specific indicator',
    indicators: 'Indicators in this window', indicatorsHelp: 'Figures come from Tracking within this reporting window. They are not typed again here.', target: 'Target', achieved: 'Achieved', execution: 'Execution', noIndicators: 'This unit has no indicators for the selected year.',
    scheduled: 'Annual Plan activities in this window', scheduledHelp: 'Automatic reference from the unit calendar.', noScheduled: 'There are no scheduled activities in this reporting window.',
    challenges: 'Challenges or pending issues', next: 'Next steps', addChallenge: '＋ Add challenge', addNext: '＋ Add next step', reviewer: 'Finance observations',
    saveDraft: 'Save draft', send: 'Send report to Finance', reviewed: 'Mark reviewed', approve: 'Approve report', saving: 'Saving…', saved: 'Report updated.', close: 'Close', remove: 'Remove',
    destination: 'Final accountability', flow: 'The unit prepares and submits. Finance receives, reviews and approves.', noObjectives: 'This unit has no objectives in the Annual Work Plan yet.', linkPlan: 'Open Annual Work Plan', missingLink: 'Every statement must be linked to at least one objective.',
    windowRange: 'Reporting period', annual: 'Annual report', periodic: 'Executive Board window', reviewerOnly: 'Finance review mode: unit content is read-only while you can add observations or approve.', consolidatedTitle: 'INSTITUTIONAL CONSOLIDATED REPORT', managementByUnit: 'Reports by unit', loading: 'Loading reports…', noItems: 'No information recorded.',
  },
}

function readLanguage(){try{return document.documentElement.lang==='en'||window.localStorage.getItem('edifica-language')==='en'?'en':'es'}catch{return'es'}}
function formatDate(value,language){if(!value)return'—';return new Intl.DateTimeFormat(language==='en'?'en-US':'es-VE',{dateStyle:'medium'}).format(new Date(`${String(value).slice(0,10)}T12:00:00`))}
function formatNumber(value,language){return new Intl.NumberFormat(language==='en'?'en-US':'es-VE',{maximumFractionDigits:2}).format(Number(value||0))}
function latestProgress(rows){return[...rows].sort((a,b)=>new Date(b.reporting_period_end||b.reporting_period_start||b.created_at||0)-new Date(a.reporting_period_end||a.reporting_period_start||a.created_at||0))[0]}
function aggregateIndicator(indicator,rows){
  const data=rows.filter((row)=>row.indicator_id===indicator.id&&row.status!=='draft')
  if(!data.length)return{value:null,text:'',completion:0}
  if(indicator.metric_type==='text')return{value:null,text:latestProgress(data)?.text_value||'',completion:0}
  if(indicator.metric_type==='boolean'){const value=Number(Boolean(Number(latestProgress(data)?.numeric_value||0)));return{value,text:'',completion:value*100}}
  let value=0
  if(indicator.aggregation_method==='average')value=data.reduce((sum,row)=>sum+Number(row.numeric_value||0),0)/data.length
  else if(['latest','unique_people','non_aggregable'].includes(indicator.aggregation_method))value=Number(latestProgress(data)?.numeric_value??latestProgress(data)?.numerator??0)
  else if(indicator.aggregation_method==='max')value=Math.max(...data.map((row)=>Number(row.numeric_value||0)))
  else if(indicator.aggregation_method==='calculated'){const row=latestProgress(data);value=Number(row?.denominator||0)>0?(Number(row?.numerator||0)/Number(row.denominator))*100:Number(row?.numeric_value||0)}
  else value=data.reduce((sum,row)=>sum+Number(row.numeric_value||0),0)
  const target=Number(indicator.target_value||0);return{value,text:'',completion:target>0?Math.round(value/target*1000)/10:0}
}
function metricDisplay(value,indicator,language){if(value===null||value===undefined||Number.isNaN(Number(value)))return'—';if(indicator.metric_type==='currency')return new Intl.NumberFormat(language==='en'?'en-US':'es-VE',{style:'currency',currency:indicator.currency||'USD',maximumFractionDigits:2}).format(Number(value));if(indicator.metric_type==='percentage')return`${formatNumber(value,language)}%`;if(indicator.metric_type==='boolean')return Number(value)?(language==='en'?'Yes':'Sí'):(language==='en'?'No':'No');return`${formatNumber(value,language)}${indicator.unit_label?` ${indicator.unit_label}`:''}`}
function emptyForm(){return{id:'',executive_summary:'',statements:[{statement:'',objective_id:'',indicator_id:''}],challenges:[''],next_steps:[''],reviewer_notes:'',status:'draft'}}
function SimpleListEditor({title,values,onChange,addLabel,readOnly}){const update=(i,v)=>onChange(values.map((item,index)=>index===i?v:item));const remove=(i)=>{const next=values.filter((_,index)=>index!==i);onChange(next.length?next:[''])};return <section className="cycle-list-editor"><div className="cycle-section-heading"><h3>{title}</h3>{!readOnly&&<button type="button" onClick={()=>onChange([...values,''])}>{addLabel}</button>}</div><div>{values.map((value,index)=><div className="cycle-simple-row" key={index}><span>{index+1}</span><textarea value={value} readOnly={readOnly} onChange={(e)=>update(index,e.target.value)}/>{!readOnly&&<button type="button" onClick={()=>remove(index)}>×</button>}</div>)}</div></section>}

export default function ManagementReportsUnifiedPage(){
  const access=useOperatorAccess();const [language,setLanguage]=useState(readLanguage);const t=copy[language]
  const canAdmin=access.role==='admin'||access.role==='super_admin';const isSuperAdmin=access.role==='super_admin'
  const [organizations,setOrganizations]=useState([]);const [organizationId,setOrganizationId]=useState(access.organizationId||'')
  const [periods,setPeriods]=useState([]);const [reportWindows,setReportWindows]=useState([]);const [units,setUnits]=useState([]);const [memberships,setMemberships]=useState([]);const [workPlans,setWorkPlans]=useState([])
  const [reports,setReports]=useState([]);const [items,setItems]=useState([]);const [indicators,setIndicators]=useState([]);const [progress,setProgress]=useState([]);const [objectives,setObjectives]=useState([]);const [assignments,setAssignments]=useState([]);const [activities,setActivities]=useState([]);const [projects,setProjects]=useState([]);const [financeAccess,setFinanceAccess]=useState(null)
  const [activePeriodId,setActivePeriodId]=useState('');const [activeWindowId,setActiveWindowId]=useState('');const [selectedUnitId,setSelectedUnitId]=useState('');const [viewMode,setViewMode]=useState('list');const [editorOpen,setEditorOpen]=useState(false);const [reviewMode,setReviewMode]=useState(false);const [form,setForm]=useState(emptyForm);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')

  useEffect(()=>{const observer=new MutationObserver(()=>setLanguage(readLanguage()));observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});return()=>observer.disconnect()},[])
  useEffect(()=>{if(access.status==='authorized')setOrganizationId((current)=>current||access.organizationId||'')},[access.organizationId,access.status])
  const loadOrganizations=useCallback(async()=>{if(!supabase||access.status!=='authorized')return;if(!isSuperAdmin){setOrganizations(access.organizationId?[{id:access.organizationId,name:access.organizationName}]:[]);return}const{data,error:requestError}=await supabase.rpc('admin_list_organizations');if(requestError)setError(requestError.message);else{setOrganizations(data??[]);setOrganizationId((current)=>current||data?.find((item)=>item.code==='cnbv')?.id||data?.[0]?.id||'')}},[access.organizationId,access.organizationName,access.status,isSuperAdmin])
  const reload=useCallback(async()=>{if(!supabase||access.status!=='authorized'||!organizationId){setLoading(false);return}setLoading(true);setError('');const responses=await Promise.all([
    supabase.from('management_period').select('*').eq('organization_id',organizationId).order('start_date',{ascending:false}),
    supabase.from('management_report_window').select('*').eq('organization_id',organizationId).eq('active',true).order('sort_order'),
    supabase.from('organization_unit').select('*').eq('organization_id',organizationId).eq('active',true).order('sort_order').order('name'),
    supabase.from('organization_unit_member').select('*').eq('organization_id',organizationId).eq('active',true),
    supabase.from('unit_work_plan').select('*').eq('organization_id',organizationId),
    supabase.from('unit_management_report').select('*').eq('organization_id',organizationId).order('updated_at',{ascending:false}),
    supabase.from('unit_management_report_item').select('*').eq('organization_id',organizationId).order('sort_order'),
    supabase.from('management_indicator').select('*').eq('organization_id',organizationId).eq('active',true).order('created_at'),
    supabase.from('indicator_progress').select('*').eq('organization_id',organizationId).order('created_at'),
    supabase.from('institutional_objective').select('*').eq('organization_id',organizationId).order('code'),
    supabase.from('objective_unit_assignment').select('*').eq('organization_id',organizationId),
    supabase.from('unit_work_activity').select('*').eq('organization_id',organizationId).order('start_date'),
    supabase.from('project').select('id,organization_id,code,name,status,project_type').eq('organization_id',organizationId).order('created_at',{ascending:false}),
    supabase.rpc('finance_access_overview',{target_organization_id:organizationId}),
  ]);const firstError=responses.find((response)=>response.error)?.error;if(firstError)setError(firstError.message);else{const periodRows=responses[0].data??[];setPeriods(periodRows);setReportWindows(responses[1].data??[]);setUnits(responses[2].data??[]);setMemberships(responses[3].data??[]);setWorkPlans(responses[4].data??[]);setReports(responses[5].data??[]);setItems(responses[6].data??[]);setIndicators(responses[7].data??[]);setProgress(responses[8].data??[]);setObjectives(responses[9].data??[]);setAssignments(responses[10].data??[]);setActivities(responses[11].data??[]);setProjects(responses[12].data??[]);setFinanceAccess(responses[13].data??null);setActivePeriodId((current)=>current&&periodRows.some((period)=>period.id===current)?current:periodRows.find((period)=>period.status==='active')?.id||periodRows[0]?.id||'')}setLoading(false)},[access.status,organizationId])
  useEffect(()=>{loadOrganizations()},[loadOrganizations]);useEffect(()=>{reload()},[reload])

  const canReview=Boolean(financeAccess?.can_manage_finance);const memberUnitIds=useMemo(()=>new Set(financeAccess?.unit_ids??memberships.filter((item)=>['director','manager','operator','reviewer'].includes(item.unit_role)).map((item)=>item.unit_id)),[financeAccess?.unit_ids,memberships]);const canManageUnit=useCallback((unitId)=>canAdmin||memberUnitIds.has(unitId),[canAdmin,memberUnitIds]);const visibleUnits=useMemo(()=>(canReview||canAdmin)?units:units.filter((unit)=>memberUnitIds.has(unit.id)),[canReview,canAdmin,units,memberUnitIds]);useEffect(()=>{if(!visibleUnits.some((unit)=>unit.id===selectedUnitId))setSelectedUnitId(visibleUnits[0]?.id||'')},[selectedUnitId,visibleUnits])
  const periodWindows=useMemo(()=>reportWindows.filter((item)=>item.management_period_id===activePeriodId),[reportWindows,activePeriodId]);useEffect(()=>{if(!periodWindows.some((item)=>item.id===activeWindowId))setActiveWindowId(periodWindows[0]?.id||'')},[periodWindows,activeWindowId]);const activeWindow=periodWindows.find((item)=>item.id===activeWindowId);const activePeriod=periods.find((item)=>item.id===activePeriodId);const diafUnit=units.find((unit)=>String(unit.code||'').trim().toUpperCase()==='DIAF')
  const reportFor=useCallback((unitId)=>{const exact=reports.find((report)=>report.unit_id===unitId&&report.report_window_id===activeWindowId);if(exact)return exact;if(activeWindow?.window_type==='annual')return reports.find((report)=>report.unit_id===unitId&&report.management_period_id===activePeriodId&&!report.report_window_id);return null},[reports,activeWindowId,activeWindow,activePeriodId])
  const currentReports=useMemo(()=>visibleUnits.map((unit)=>reportFor(unit.id)).filter(Boolean),[visibleUnits,reportFor]);const submittedCount=currentReports.filter((report)=>['submitted','reviewed','approved','closed'].includes(report.status)).length;const approvedCount=currentReports.filter((report)=>['approved','closed'].includes(report.status)).length
  const rowInsideWindow=useCallback((row)=>{if(!activeWindow)return false;const raw=row.reporting_period_end||row.reporting_period_start||String(row.created_at||'').slice(0,10);if(!raw)return false;return raw>=activeWindow.start_date&&raw<=activeWindow.end_date},[activeWindow]);const windowProgress=useMemo(()=>progress.filter(rowInsideWindow),[progress,rowInsideWindow])
  const unitPlan=(unitId)=>workPlans.find((plan)=>plan.management_period_id===activePeriodId&&plan.unit_id===unitId);const unitObjectives=(unitId)=>{const plan=unitPlan(unitId);return objectives.filter((objective)=>objective.management_period_id===activePeriodId&&(plan?objective.work_plan_id===plan.id:assignments.some((assignment)=>assignment.objective_id===objective.id&&assignment.assignment_type==='responsible'&&assignment.unit_id===unitId)))};const unitIndicators=(unitId)=>indicators.filter((indicator)=>indicator.management_period_id===activePeriodId&&indicator.unit_id===unitId)
  const reportItems=(report,type)=>report?items.filter((item)=>item.report_id===report.id&&item.item_type===type).sort((a,b)=>a.sort_order-b.sort_order):[]
  const activitiesForWindow=(unitId)=>{const plan=unitPlan(unitId);if(!plan||!activeWindow)return[];return activities.filter((activity)=>activity.work_plan_id===plan.id&&activity.start_date<=activeWindow.end_date&&(activity.end_date||activity.start_date)>=activeWindow.start_date)}

  const hydrateForm=(unitId,asReview=false)=>{const report=reportFor(unitId);const achievements=reportItems(report,'achievement');setSelectedUnitId(unitId);setForm(report?{id:report.id,executive_summary:report.executive_summary||'',statements:achievements.length?achievements.map((item)=>({statement:item.statement,objective_id:item.objective_id||objectives.find((objective)=>objective.id===indicators.find((indicator)=>indicator.id===item.indicator_id)?.objective_id)?.id||'',indicator_id:item.indicator_id||''})):[{statement:'',objective_id:'',indicator_id:''}],challenges:reportItems(report,'challenge').map((item)=>item.statement).length?reportItems(report,'challenge').map((item)=>item.statement):[''],next_steps:reportItems(report,'next_step').map((item)=>item.statement).length?reportItems(report,'next_step').map((item)=>item.statement):[''],reviewer_notes:report.reviewer_notes||'',status:report.status}:emptyForm());setReviewMode(asReview);setEditorOpen(true);setViewMode('list');setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
  const updateStatement=(index,patch)=>setForm((current)=>({...current,statements:current.statements.map((row,i)=>i===index?{...row,...patch}:row)}));const addStatement=()=>setForm((current)=>({...current,statements:[...current.statements,{statement:'',objective_id:'',indicator_id:''}]}));const removeStatement=(index)=>setForm((current)=>{const next=current.statements.filter((_,i)=>i!==index);return{...current,statements:next.length?next:[{statement:'',objective_id:'',indicator_id:''}]}})

  const saveReport=async(status)=>{if(saving||!selectedUnitId||!activeWindowId)return;const reviewStatus=['reviewed','approved','closed'].includes(status);if(reviewStatus&&!canReview)return;if(!reviewStatus&&!canManageUnit(selectedUnitId)&&!canReview)return;const activeStatements=form.statements.filter((row)=>row.statement.trim());if(activeStatements.some((row)=>!row.objective_id&&!row.indicator_id)){setError(t.missingLink);return}const payloadItems=[];activeStatements.forEach((row)=>payloadItems.push({item_type:'achievement',statement:row.statement.trim(),objective_id:row.objective_id||null,indicator_id:row.indicator_id||null}));form.challenges.map((statement)=>statement.trim()).filter(Boolean).forEach((statement)=>payloadItems.push({item_type:'challenge',statement}));form.next_steps.map((statement)=>statement.trim()).filter(Boolean).forEach((statement)=>payloadItems.push({item_type:'next_step',statement}));setSaving(true);setError('');setMessage('');const{data:reportId,error:requestError}=await supabase.rpc('save_unit_management_report_v4',{payload:{id:form.id,organization_id:organizationId,report_window_id:activeWindowId,unit_id:selectedUnitId,status,executive_summary:form.executive_summary,reviewer_notes:form.reviewer_notes,items:payloadItems}});if(requestError)setError(requestError.message);else{setForm((current)=>({...current,id:reportId,status}));setMessage(t.saved);await reload()}setSaving(false)}

  const renderIndicator=(indicator)=>{const result=aggregateIndicator(indicator,windowProgress);const objective=objectives.find((item)=>item.id===indicator.objective_id);return <article className="cycle-indicator-card" key={indicator.id}><header><div><small>{kindLabels[language][indicator.indicator_kind||'result']} · {objective?.code||''}</small><strong>{indicator.name}</strong></div><span>{indicator.frequency}</span></header><div><div><span>{t.target}</span><b>{indicator.target_value==null?indicator.target_text||'—':metricDisplay(indicator.target_value,indicator,language)}</b></div><div><span>{t.achieved}</span><b>{result.text||metricDisplay(result.value,indicator,language)}</b></div><div><span>{t.execution}</span><b>{formatNumber(result.completion,language)}%</b></div></div><div className="cycle-progress"><span style={{width:`${Math.min(Math.max(result.completion,0),100)}%`}}/></div></article>}

  const renderDocument=(unit)=>{const report=reportFor(unit.id);const statementRows=reportItems(report,'achievement');const challenges=reportItems(report,'challenge');const nextSteps=reportItems(report,'next_step');const currentIndicators=unitIndicators(unit.id);return <section className="cycle-report-document"><header><div><small>{t.report}</small><h1>{unit.code} · {unit.name}</h1><p>{activeWindow?.title} · {activePeriod?.name}</p></div><div className="unit-report-v2-actions no-print"><button onClick={()=>setViewMode('list')}>{t.back}</button><button className="primary" onClick={()=>window.print()}>{t.print}</button></div></header><div className="cycle-route"><span>{t.destination}</span><strong>{diafUnit?`${diafUnit.code} · ${diafUnit.name}`:'DIAF'}</strong><small>{t.flow}</small></div>{report?.executive_summary&&<section><h2>{t.executive}</h2><p>{report.executive_summary}</p></section>}<section><h2>{t.statements}</h2>{statementRows.length?<ol className="cycle-document-statements">{statementRows.map((item)=><li key={item.id}><p>{item.statement}</p><small>{objectives.find((objective)=>objective.id===item.objective_id)?.code||''}{item.indicator_id?` · ${indicators.find((indicator)=>indicator.id===item.indicator_id)?.name||''}`:''}</small></li>)}</ol>:<p className="report-empty-text">{t.noItems}</p>}</section><section><h2>{t.indicators}</h2><div className="cycle-indicator-grid">{currentIndicators.length?currentIndicators.map(renderIndicator):<p className="report-empty-text">{t.noIndicators}</p>}</div></section>{challenges.length>0&&<section><h2>{t.challenges}</h2><ol className="unit-report-items">{challenges.map((item)=><li key={item.id}>{item.statement}</li>)}</ol></section>}{nextSteps.length>0&&<section><h2>{t.next}</h2><ol className="unit-report-items">{nextSteps.map((item)=><li key={item.id}>{item.statement}</li>)}</ol></section>}{report?.reviewer_notes&&<section><h2>{t.reviewer}</h2><p>{report.reviewer_notes}</p></section>}</section>}
  const renderConsolidated=()=> <section className="cycle-report-document consolidated-v2"><header><div><small>{t.consolidatedTitle}</small><h1>{activeWindow?.title}</h1><p>{activePeriod?.name}</p></div><div className="unit-report-v2-actions no-print"><button onClick={()=>setViewMode('list')}>{t.back}</button><button className="primary" onClick={()=>window.print()}>{t.print}</button></div></header><div className="consolidated-v2-summary"><article><span>{t.units}</span><strong>{visibleUnits.length}</strong></article><article><span>{t.started}</span><strong>{currentReports.length}</strong></article><article><span>{t.submitted}</span><strong>{submittedCount}</strong></article><article><span>{t.approved}</span><strong>{approvedCount}</strong></article></div><section><h2>{t.managementByUnit}</h2><div className="cycle-consolidated-units">{visibleUnits.map((unit)=>{const report=reportFor(unit.id);if(!report)return null;return <article key={unit.id}><header><span>{unit.code}</span><div><h3>{unit.name}</h3><small>{statusLabels[language][report.status]}</small></div></header>{report.executive_summary&&<p>{report.executive_summary}</p>}<ol>{reportItems(report,'achievement').map((item)=><li key={item.id}>{item.statement}</li>)}</ol><div className="cycle-indicator-grid compact">{unitIndicators(unit.id).map(renderIndicator)}</div></article>})}</div></section></section>

  if(access.status!=='authorized')return <OperatorAccessScreen access={access} copy={{languageLabel:language==='en'?'Language':'Idioma'}} language={language} onLanguageChange={()=>{}}/>
  const selectedUnit=units.find((unit)=>unit.id===selectedUnitId);const selectedReport=reportFor(selectedUnitId);const selectedObjectives=unitObjectives(selectedUnitId);const selectedIndicators=unitIndicators(selectedUnitId);const selectedActivities=activitiesForWindow(selectedUnitId);const readOnlyEditor=reviewMode||!canManageUnit(selectedUnitId)

  return <ManagementStandaloneShell access={access}><div className="management-panel cycle-reports-page"><div className="management-panel-heading no-print"><div><p>{t.eyebrow}</p><h1>{t.title}</h1><span>{t.intro}</span></div><button onClick={()=>{setEditorOpen(false);setViewMode(viewMode==='consolidated'?'list':'consolidated')}}>{viewMode==='consolidated'?t.back:t.consolidated}</button></div>{isSuperAdmin&&<section className="management-filter-row no-print"><label><span>{t.organization}</span><select value={organizationId} onChange={(event)=>setOrganizationId(event.target.value)}>{organizations.map((organization)=><option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></label></section>}{error&&<p className="management-flash error">{error}</p>}{message&&<p className="management-flash success">{message}</p>}
    {loading?<div className="management-loading"><span/><p>{t.loading}</p></div>:viewMode==='unit'&&selectedUnit?renderDocument(selectedUnit):viewMode==='consolidated'?renderConsolidated():<>
      <section className="cycle-report-context no-print"><label><span>{t.year}</span><select value={activePeriodId} onChange={(event)=>{setActivePeriodId(event.target.value);setActiveWindowId('');setEditorOpen(false)}}>{periods.map((period)=><option key={period.id} value={period.id}>{period.name}</option>)}</select></label><label className="wide"><span>{t.window}</span><select value={activeWindowId} onChange={(event)=>{setActiveWindowId(event.target.value);setEditorOpen(false)}}>{periodWindows.map((window)=><option key={window.id} value={window.id}>{window.title}</option>)}</select></label>{activeWindow&&<div><small>{activeWindow.window_type==='annual'?t.annual:t.periodic}</small><strong>{formatDate(activeWindow.start_date,language)} — {formatDate(activeWindow.end_date,language)}</strong><span>{t.windowRange}</span></div>}</section>
      <section className="management-report-summary no-print"><article><span>{t.units}</span><strong>{visibleUnits.length}</strong></article><article><span>{t.started}</span><strong>{currentReports.length}</strong></article><article><span>{t.submitted}</span><strong>{submittedCount}</strong></article><article><span>{t.approved}</span><strong>{approvedCount}</strong></article></section>

      {editorOpen&&selectedUnit&&<section className="management-form-card cycle-report-editor no-print"><div className="management-form-title"><div><small>{t.report}</small><h2>{selectedUnit.code} · {selectedUnit.name}</h2><p>{activeWindow?.title} · {activePeriod?.name}</p><span className={`report-state ${form.status}`}>{statusLabels[language][form.status]}</span></div><button type="button" onClick={()=>setEditorOpen(false)}>{t.close}</button></div><div className="cycle-route"><span>{t.destination}</span><strong>{diafUnit?`${diafUnit.code} · ${diafUnit.name}`:'DIAF'}</strong><small>{t.flow}</small></div>{reviewMode&&<div className="unified-review-note">{t.reviewerOnly}</div>}
        <label className="cycle-summary"><span>{t.executive}</span><small>{t.executiveHelp}</small><textarea value={form.executive_summary} readOnly={readOnlyEditor} onChange={(event)=>setForm((current)=>({...current,executive_summary:event.target.value}))}/></label>

        <section className="cycle-statements"><div className="cycle-section-heading"><div><h3>{t.statements}</h3><p>{t.statementsHelp}</p></div>{!readOnlyEditor&&<button type="button" onClick={addStatement}>{t.addStatement}</button>}</div>{!selectedObjectives.length&&<div className="cycle-no-objectives"><p>{t.noObjectives}</p><a href={`/app/management/objectives?period=${encodeURIComponent(activePeriodId)}&unit=${encodeURIComponent(selectedUnitId)}`}>{t.linkPlan}</a></div>}<div className="cycle-statement-list">{form.statements.map((row,index)=>{const availableIndicators=selectedIndicators.filter((indicator)=>!row.objective_id||indicator.objective_id===row.objective_id);return <div className="cycle-statement-row" key={index}><span>{index+1}</span><div><textarea value={row.statement} readOnly={readOnlyEditor} placeholder={t.statement} onChange={(event)=>updateStatement(index,{statement:event.target.value})}/><div className="cycle-statement-links"><label><small>{t.objective} *</small><select value={row.objective_id} disabled={readOnlyEditor} onChange={(event)=>updateStatement(index,{objective_id:event.target.value,indicator_id:''})}><option value="">{t.selectObjective}</option>{selectedObjectives.map((objective)=><option key={objective.id} value={objective.id}>{objective.code} · {objective.title}</option>)}</select></label><label><small>{t.indicator}</small><select value={row.indicator_id} disabled={readOnlyEditor} onChange={(event)=>{const indicator=selectedIndicators.find((item)=>item.id===event.target.value);updateStatement(index,{indicator_id:event.target.value,objective_id:indicator?.objective_id||row.objective_id})}}><option value="">{t.selectIndicator}</option>{availableIndicators.map((indicator)=><option key={indicator.id} value={indicator.id}>{indicator.name}</option>)}</select></label></div></div>{!readOnlyEditor&&<button type="button" onClick={()=>removeStatement(index)}>×</button>}</div>})}</div></section>

        <section className="cycle-indicators-section"><div className="cycle-section-heading"><div><h3>{t.indicators}</h3><p>{t.indicatorsHelp}</p></div></div><div className="cycle-indicator-grid">{selectedIndicators.length?selectedIndicators.map(renderIndicator):<div className="cycle-no-objectives"><p>{t.noIndicators}</p><a href={`/app/management/objectives?period=${encodeURIComponent(activePeriodId)}&unit=${encodeURIComponent(selectedUnitId)}`}>{t.linkPlan}</a></div>}</div></section>

        <section className="cycle-scheduled-section"><div className="cycle-section-heading"><div><h3>{t.scheduled}</h3><p>{t.scheduledHelp}</p></div></div>{selectedActivities.length?<div className="cycle-scheduled-list">{selectedActivities.map((activity)=><article key={activity.id}><span>{formatDate(activity.start_date,language)}</span><div><strong>{activity.title}</strong><small>{objectives.find((objective)=>objective.id===activity.objective_id)?.code||''} · {activity.status}</small></div></article>)}</div>:<p className="report-empty-text">{t.noScheduled}</p>}</section>

        <SimpleListEditor title={t.challenges} values={form.challenges} onChange={(values)=>setForm((current)=>({...current,challenges:values}))} addLabel={t.addChallenge} readOnly={readOnlyEditor}/><SimpleListEditor title={t.next} values={form.next_steps} onChange={(values)=>setForm((current)=>({...current,next_steps:values}))} addLabel={t.addNext} readOnly={readOnlyEditor}/>{canReview&&<label className="cycle-summary"><span>{t.reviewer}</span><textarea value={form.reviewer_notes} onChange={(event)=>setForm((current)=>({...current,reviewer_notes:event.target.value}))}/></label>}
        <div className="report-actions unified-report-actions">{canManageUnit(selectedUnitId)&&!reviewMode&&<><button onClick={()=>saveReport('draft')} disabled={saving}>{t.saveDraft}</button><button className="primary" onClick={()=>saveReport('submitted')} disabled={saving}>{saving?t.saving:t.send}</button></>}{canReview&&form.id&&<><button onClick={()=>saveReport('reviewed')} disabled={saving}>{t.reviewed}</button><button className="approve" onClick={()=>saveReport('approved')} disabled={saving}>{t.approve}</button></>}</div>
      </section>}

      <section className="management-report-status management-unit-report-directory"><div className="management-card-heading"><div><small>{t.directory}</small><h2>{t.directoryTitle}</h2><p>{t.directoryHelp}</p></div></div><div>{visibleUnits.map((unit)=>{const report=reportFor(unit.id);return <article key={unit.id}><span>{unit.code}</span><div><strong>{unit.name}</strong><small>{report?`${t.updated} ${formatDate(report.updated_at,language)}`:t.pending}</small></div><b className={`report-state ${report?.status||'none'}`}>{statusLabels[language][report?.status||'none']}</b><div className="unit-report-row-actions"><button onClick={()=>{setSelectedUnitId(unit.id);setEditorOpen(false);setViewMode('unit');window.scrollTo({top:0,behavior:'smooth'})}}>{t.view}</button>{canManageUnit(unit.id)&&<button className="secondary" onClick={()=>hydrateForm(unit.id,false)}>{report?t.edit:t.create}</button>}{canReview&&report&&['submitted','reviewed','approved'].includes(report.status)&&<button className="primary" onClick={()=>hydrateForm(unit.id,true)}>{t.review}</button>}</div></article>})}</div></section>
    </>}
  </div></ManagementStandaloneShell>
}
