export const content = {
  es: {
    meta: {
      title: 'Edifica Digital | Trazabilidad humanitaria',
      description: 'Edifica Digital: trazabilidad de donaciones, evidencias de gestión y reportes institucionales.',
    },
    nav: {
      process: 'Proceso',
      platform: 'Plataforma',
      reports: 'Reportes',
      cta: 'Solicitar presentación',
      menu: 'Abrir menú',
      landmark: 'Navegación principal',
      home: 'Edifica Digital, inicio',
      label: 'Cambiar idioma a inglés',
      current: 'ES',
      alternate: 'EN',
    },
    hero: {
      eyebrow: 'Tecnología para la gestión social',
      title: 'La ruta completa de cada donación, en un solo lugar.',
      lead: 'Una plataforma para registrar recursos, documentar su transformación y presentar el impacto de cada entrega con evidencias organizadas.',
      primary: 'Conocer la propuesta',
      secondary: 'Explorar el proceso',
      note: 'Diseñada para fundaciones, organizaciones sociales, iglesias y equipos de respuesta humanitaria.',
      visualLabel: 'Vista previa del panel de Edifica Digital',
    },
    dashboard: {
      summary: 'RESUMEN GENERAL',
      title: 'Panel de impacto',
      period: 'Últimos 30 días',
      received: 'RECURSOS RECIBIDOS',
      receivedNote: 'unidades registradas',
      prepared: 'KITS PREPARADOS',
      preparedNote: 'con soporte asociado',
      people: 'PERSONAS ATENDIDAS',
      peopleNote: 'en 28 jornadas',
      activity: 'ACTIVIDAD',
      chart: 'Recursos e impacto',
      register: 'Registro',
      delivery: 'Entrega',
      evidence: 'EVIDENCIA VINCULADA',
      evidenceName: 'Acta de entrega · Jornada 028',
    },
    trust: {
      title: 'Información organizada para decisiones responsables',
      items: ['TRAZABILIDAD', 'EVIDENCIAS', 'INDICADORES', 'REPORTES'],
    },
    process: {
      kicker: 'EL RECORRIDO',
      title: 'Recibir. Transformar. Impactar.',
      intro: 'Tres momentos documentados dentro de una misma operación. Cada registro conserva sus datos, responsables y archivos.',
      stages: [
        {
          number: '01',
          title: 'Recibir',
          text: 'Registro de aportes monetarios y donaciones en especie, con datos del donante y comprobantes asociados.',
          note: 'Origen y recepción',
        },
        {
          number: '02',
          title: 'Transformar',
          text: 'Control de insumos, elaboración de kits y documentos fiscales vinculados a cada jornada de preparación.',
          note: 'Recursos preparados',
        },
        {
          number: '03',
          title: 'Impactar',
          text: 'Registro de entregas, población atendida, responsables, fotografías y soportes de cada actividad.',
          note: 'Resultados verificables',
        },
      ],
    },
    platform: {
      eyebrow: 'Gestión documentada',
      title: 'Una estructura clara para el trabajo diario.',
      intro: 'Formularios sencillos, archivos vinculados y paneles con indicadores para equipos que gestionan recursos y actividades en campo.',
      features: [
        'Registro de donantes y organizaciones',
        'Donaciones monetarias y en especie',
        'Control de kits y jornadas de preparación',
        'Demografía, entregas y evidencias',
        'Panel global y vista por campaña',
      ],
      event: 'JORNADA DE IMPACTO',
      status: 'Estado: cerrada',
      eventName: 'Respuesta comunitaria · La Guaira',
      eventDate: '16 de julio de 2026 · Responsable de jornada',
      metrics: [
        ['1.124', 'Hidrataciones'],
        ['1.151', 'Kits de higiene'],
        ['1.056', 'Atenciones médicas'],
      ],
      photo: 'Registro fotográfico',
      photoCount: '12 archivos',
      support: 'Actas y soportes',
      supportCount: '4 archivos',
    },
    reports: {
      kicker: 'RENDICIÓN DE CUENTAS',
      title: 'Reportes preparados para revisión institucional.',
      intro: 'Información consolidada para directivas, donantes, aliados y organizaciones internacionales que soliciten resultados de gestión.',
      previewLabel: 'Muestra de reporte institucional',
      reportType: 'REPORTE INSTITUCIONAL · 2026',
      area: 'RESPUESTA HUMANITARIA',
      reportTitle: 'Informe de gestión e impacto',
      period: 'Período documentado: 24 de junio — 16 de julio',
      metrics: [
        ['6.100', 'Personas atendidas'],
        ['4,8 t', 'Recursos gestionados'],
        ['28', 'Jornadas registradas'],
      ],
      footer: 'Datos consolidados y evidencias anexas',
      export: 'EXPORTACIÓN · PDF',
      copyTitle: 'Información lista para presentar.',
      copy: 'El reporte reúne indicadores, relación de recursos y evidencia documental dentro de un archivo formal para evaluación, auditoría y cooperación.',
      items: [
        'Resumen ejecutivo de la operación',
        'Indicadores de personas y familias atendidas',
        'Relación de recursos recibidos y entregados',
        'Galería de evidencias y documentos',
      ],
      languages: 'Preparación prevista en español e inglés para procesos de cooperación internacional.',
    },
    closing: {
      title: 'Trazabilidad que respalda cada resultado.',
      copy: 'Conoce la propuesta funcional, el alcance del primer lanzamiento y las posibilidades de implementación para tu organización.',
      cta: 'Solicitar presentación',
      whatsapp: 'Hola, quisiera conocer la propuesta de Edifica Digital.',
    },
    footer: {
      copy: 'Plataforma de trazabilidad y gestión de impacto.',
    },
  },
  en: {
    meta: {
      title: 'Edifica Digital | Humanitarian traceability',
      description: 'Edifica Digital: donation traceability, management evidence and institutional reporting.',
    },
    nav: {
      process: 'Process',
      platform: 'Platform',
      reports: 'Reports',
      cta: 'Request a presentation',
      menu: 'Open menu',
      landmark: 'Main navigation',
      home: 'Edifica Digital, home',
      label: 'Cambiar idioma a español',
      current: 'EN',
      alternate: 'ES',
    },
    hero: {
      eyebrow: 'Technology for social management',
      title: 'The complete path of every donation, in one place.',
      lead: 'A platform to register resources, document their transformation and present the impact of every delivery with organized evidence.',
      primary: 'Explore the proposal',
      secondary: 'View the process',
      note: 'Designed for foundations, social organizations, churches and humanitarian response teams.',
      visualLabel: 'Preview of the Edifica Digital dashboard',
    },
    dashboard: {
      summary: 'GENERAL OVERVIEW',
      title: 'Impact dashboard',
      period: 'Last 30 days',
      received: 'RESOURCES RECEIVED',
      receivedNote: 'registered units',
      prepared: 'KITS PREPARED',
      preparedNote: 'with supporting records',
      people: 'PEOPLE REACHED',
      peopleNote: 'across 28 activities',
      activity: 'ACTIVITY',
      chart: 'Resources and impact',
      register: 'Recorded',
      delivery: 'Delivered',
      evidence: 'LINKED EVIDENCE',
      evidenceName: 'Delivery record · Activity 028',
    },
    trust: {
      title: 'Organized information for responsible decisions',
      items: ['TRACEABILITY', 'EVIDENCE', 'INDICATORS', 'REPORTS'],
    },
    process: {
      kicker: 'THE PROCESS',
      title: 'Receive. Transform. Impact.',
      intro: 'Three documented stages within a single operation. Each record retains its data, responsible parties and files.',
      stages: [
        {
          number: '01',
          title: 'Receive',
          text: 'Registration of monetary and in-kind donations, including donor information and supporting documents.',
          note: 'Origin and receipt',
        },
        {
          number: '02',
          title: 'Transform',
          text: 'Control of supplies, kit assembly and fiscal documents linked to each preparation activity.',
          note: 'Resources prepared',
        },
        {
          number: '03',
          title: 'Impact',
          text: 'Registration of deliveries, population reached, responsible teams, photographs and supporting records.',
          note: 'Verifiable results',
        },
      ],
    },
    platform: {
      eyebrow: 'Documented management',
      title: 'A clear structure for daily operations.',
      intro: 'Simple forms, linked files and indicator dashboards for teams managing resources and field activities.',
      features: [
        'Donor and organization records',
        'Monetary and in-kind donations',
        'Kit and preparation activity control',
        'Demographics, deliveries and evidence',
        'Global dashboard and campaign view',
      ],
      event: 'IMPACT ACTIVITY',
      status: 'Status: closed',
      eventName: 'Community response · La Guaira',
      eventDate: 'July 16, 2026 · Activity manager',
      metrics: [
        ['1,124', 'Hydration services'],
        ['1,151', 'Hygiene kits'],
        ['1,056', 'Medical services'],
      ],
      photo: 'Photographic record',
      photoCount: '12 files',
      support: 'Records and documents',
      supportCount: '4 files',
    },
    reports: {
      kicker: 'ACCOUNTABILITY',
      title: 'Reports prepared for institutional review.',
      intro: 'Consolidated information for boards, donors, partners and international organizations requesting management results.',
      previewLabel: 'Institutional report preview',
      reportType: 'INSTITUTIONAL REPORT · 2026',
      area: 'HUMANITARIAN RESPONSE',
      reportTitle: 'Management and impact report',
      period: 'Documented period: June 24 — July 16',
      metrics: [
        ['6,100', 'People reached'],
        ['4.8 t', 'Resources managed'],
        ['28', 'Activities recorded'],
      ],
      footer: 'Consolidated data and supporting evidence',
      export: 'EXPORT · PDF',
      copyTitle: 'Information ready for presentation.',
      copy: 'The report includes indicators, resource records and documentary evidence in a formal file for evaluation, audit and cooperation.',
      items: [
        'Executive summary of the operation',
        'People and families reached indicators',
        'Record of resources received and delivered',
        'Evidence and document gallery',
      ],
      languages: 'Planned preparation in Spanish and English for international cooperation processes.',
    },
    closing: {
      title: 'Traceability that supports every result.',
      copy: 'Explore the functional proposal, the scope of the initial release and implementation possibilities for your organization.',
      cta: 'Request a presentation',
      whatsapp: 'Hello, I would like to learn about the Edifica Digital proposal.',
    },
    footer: {
      copy: 'Traceability and impact management platform.',
    },
  },
}
