const sharedAuth = {
  es: {
    eyebrow: 'Acceso operativo',
    title: 'Ingresa con tu correo autorizado',
    body: 'Recibirás un enlace seguro para abrir el registro de donaciones.',
    email: 'Correo del equipo',
    emailPlaceholder: 'nombre@organizacion.org',
    sendLink: 'Enviar enlace de acceso',
    sending: 'Enviando…',
    requestError: 'Revisa el correo e intenta solicitar el enlace otra vez.',
    linkEyebrow: 'Enlace enviado',
    linkTitle: 'Revisa tu correo',
    linkBody: 'Abre el enlace desde este dispositivo para continuar con el registro.',
    sendAgain: 'Enviar otro enlace',
    restrictedEyebrow: 'Acceso pendiente',
    restrictedTitle: 'Esta cuenta requiere autorización operativa',
    restrictedBody: 'El equipo responsable puede activar esta cuenta en la lista de operadores.',
    signOut: 'Usar otra cuenta',
    errorEyebrow: 'Sesión pendiente',
    errorTitle: 'Renueva el acceso',
    errorBody: 'Cierra esta sesión y solicita un enlace nuevo.',
    configurationEyebrow: 'Configuración pendiente',
    configurationTitle: 'Conecta el entorno operativo',
    configurationBody: 'Agrega la URL y la clave publicable de Supabase a las variables del proyecto.',
  },
  en: {
    eyebrow: 'Operational access',
    title: 'Sign in with your authorized email',
    body: 'You will receive a secure link to open donation intake.',
    email: 'Team email',
    emailPlaceholder: 'name@organization.org',
    sendLink: 'Send access link',
    sending: 'Sending…',
    requestError: 'Review the email and request the link again.',
    linkEyebrow: 'Link sent',
    linkTitle: 'Check your email',
    linkBody: 'Open the link on this device to continue the record.',
    sendAgain: 'Send another link',
    restrictedEyebrow: 'Access pending',
    restrictedTitle: 'This account requires operational authorization',
    restrictedBody: 'The responsible team can activate this account in the operator list.',
    signOut: 'Use another account',
    errorEyebrow: 'Session pending',
    errorTitle: 'Refresh access',
    errorBody: 'Close this session and request a new link.',
    configurationEyebrow: 'Configuration pending',
    configurationTitle: 'Connect the operational environment',
    configurationBody: 'Add the Supabase URL and publishable key to the project variables.',
  },
}

export const monetaryContent = {
  es: {
    metaTitle: 'Nueva donación monetaria | Edifica Digital',
    languageLabel: 'Cambiar idioma a inglés',
    languageCurrent: 'ES',
    languageAlternate: 'EN',
    backHome: 'Volver al inicio',
    eyebrow: 'Recepción de fondos',
    title: 'Nueva donación monetaria',
    intro: 'Registra el dinero recibido, la tasa aplicada y el comprobante en una sola pantalla. El borrador se guarda en este dispositivo.',
    requiredNote: 'Los campos marcados con * son obligatorios.',
    draftSaved: 'Borrador guardado',
    sections: {
      donor: { number: '01', title: 'Datos del donante', help: 'Usa la información disponible en el comprobante o acta de recepción.' },
      receipt: { number: '02', title: 'Dinero recibido', help: 'Conserva el monto y la moneda en que llegaron los fondos.' },
      reporting: { number: '03', title: 'Base de reporte en USD', help: 'Registra la tasa usada para mantener una conversión verificable.' },
      evidence: { number: '04', title: 'Comprobante y revisión', help: 'Adjunta evidencia legible y confirma los datos antes de guardar.' },
    },
    fields: {
      donorName: 'Nombre del donante *',
      donorNamePlaceholder: 'Ej. Donante comunitario',
      donorType: 'Tipo de donante',
      person: 'Persona',
      organization: 'Organización',
      donorContact: 'Correo o teléfono',
      donorContactHint: 'Opcional · facilita una verificación posterior',
      anonymous: 'Presentar esta donación como anónima en reportes',
      receivedAt: 'Fecha y hora de recepción *',
      paymentMethod: 'Forma de recepción *',
      originAmount: 'Monto recibido *',
      originCurrency: 'Moneda de origen *',
      senderInstitution: 'Banco o institución emisora *',
      senderInstitutionPlaceholder: 'Ej. Banco emisor',
      receiverAccountLabel: 'Cuenta o institución receptora *',
      receiverAccountPlaceholder: 'Ej. Cuenta operativa',
      transactionReference: 'Referencia de la transacción *',
      transactionReferencePlaceholder: 'Ej. 00012345',
      usdBaseAmount: 'Monto base en USD *',
      exchangeRate: 'Tasa aplicada: USD por 1 unidad de origen *',
      calculated: 'Cálculo disponible',
      applyCalculation: 'Usar este monto',
      exchangeRateSource: 'Fuente de la tasa *',
      exchangeRateSourcePlaceholder: 'Ej. BCV o documento bancario',
      exchangeRateDate: 'Fecha de la tasa *',
      notes: 'Notas de conciliación',
      notesPlaceholder: 'Dato útil para la revisión financiera',
      verification: 'Confirmo que revisé el monto, la moneda, la tasa y el comprobante.',
    },
    methods: {
      cash: 'Efectivo',
      bank_transfer: 'Transferencia bancaria',
      mobile_payment: 'Pago móvil',
      digital_wallet: 'Billetera digital',
      crypto: 'Criptoactivo',
      other: 'Otro medio',
    },
    currencies: { USD: 'USD · Dólar estadounidense', EUR: 'EUR · Euro', VES: 'VES · Bolívar venezolano' },
    evidence: {
      add: 'Agregar comprobante',
      formats: 'PDF, JPG, PNG o WebP · hasta 20 MB por archivo',
      session: 'Los archivos permanecen disponibles durante esta sesión.',
      type: 'Tipo de evidencia',
      types: { proof_of_payment: 'Comprobante de pago', receipt: 'Acta o recibo' },
      remove: 'Eliminar',
      required: 'Agrega al menos un comprobante o acta de recepción.',
      unsupported: 'Usa un archivo PDF, JPG, PNG o WebP.',
      tooLarge: 'El archivo supera 20 MB.',
    },
    actions: { save: 'Guardar donación', saving: 'Guardando…', another: 'Registrar otra donación', home: 'Ir al inicio' },
    submissionErrors: {
      authentication: 'Renueva la sesión con tu correo autorizado.',
      evidence_required: 'Agrega al menos un comprobante o acta de recepción.',
      evidence_validation: 'Revisa el formato y el tamaño de los archivos.',
      evidence_upload: 'Los archivos siguen disponibles. Intenta guardar otra vez.',
      record: 'El borrador y los archivos siguen disponibles. Intenta guardar otra vez.',
      default: 'El registro sigue disponible como borrador. Intenta guardar otra vez.',
    },
    success: {
      eyebrow: 'Registro confirmado',
      title: 'La donación monetaria quedó guardada.',
      copy: 'La referencia vincula el donante, los montos, la tasa aplicada y la evidencia.',
      reference: 'Referencia de la donación',
      note: 'El borrador local se cerró después de la confirmación de Supabase.',
    },
    auth: sharedAuth.es,
  },
  en: {
    metaTitle: 'New monetary donation | Edifica Digital',
    languageLabel: 'Cambiar idioma a español',
    languageCurrent: 'EN',
    languageAlternate: 'ES',
    backHome: 'Back to home',
    eyebrow: 'Funds received',
    title: 'New monetary donation',
    intro: 'Record the funds received, applied rate, and evidence on one screen. The draft is saved on this device.',
    requiredNote: 'Fields marked with * are required.',
    draftSaved: 'Draft saved',
    sections: {
      donor: { number: '01', title: 'Donor details', help: 'Use the information available on the evidence or receipt record.' },
      receipt: { number: '02', title: 'Funds received', help: 'Preserve the amount and currency in which the funds arrived.' },
      reporting: { number: '03', title: 'USD reporting base', help: 'Record the applied rate to keep the conversion verifiable.' },
      evidence: { number: '04', title: 'Evidence and review', help: 'Attach readable evidence and confirm the data before saving.' },
    },
    fields: {
      donorName: 'Donor name *',
      donorNamePlaceholder: 'E.g. Community donor',
      donorType: 'Donor type',
      person: 'Person',
      organization: 'Organization',
      donorContact: 'Email or phone',
      donorContactHint: 'Optional · supports later verification',
      anonymous: 'Present this donation as anonymous in reports',
      receivedAt: 'Receipt date and time *',
      paymentMethod: 'Receipt method *',
      originAmount: 'Amount received *',
      originCurrency: 'Origin currency *',
      senderInstitution: 'Sending bank or institution *',
      senderInstitutionPlaceholder: 'E.g. Sending bank',
      receiverAccountLabel: 'Receiving account or institution *',
      receiverAccountPlaceholder: 'E.g. Operating account',
      transactionReference: 'Transaction reference *',
      transactionReferencePlaceholder: 'E.g. 00012345',
      usdBaseAmount: 'USD base amount *',
      exchangeRate: 'Applied rate: USD per 1 origin unit *',
      calculated: 'Available calculation',
      applyCalculation: 'Use this amount',
      exchangeRateSource: 'Rate source *',
      exchangeRateSourcePlaceholder: 'E.g. Central bank or bank document',
      exchangeRateDate: 'Rate date *',
      notes: 'Reconciliation notes',
      notesPlaceholder: 'Useful detail for the financial review',
      verification: 'I confirm that I reviewed the amount, currency, rate, and evidence.',
    },
    methods: {
      cash: 'Cash',
      bank_transfer: 'Bank transfer',
      mobile_payment: 'Mobile payment',
      digital_wallet: 'Digital wallet',
      crypto: 'Cryptoasset',
      other: 'Other method',
    },
    currencies: { USD: 'USD · US dollar', EUR: 'EUR · Euro', VES: 'VES · Venezuelan bolívar' },
    evidence: {
      add: 'Add evidence',
      formats: 'PDF, JPG, PNG, or WebP · up to 20 MB per file',
      session: 'Files remain available during this session.',
      type: 'Evidence type',
      types: { proof_of_payment: 'Proof of payment', receipt: 'Receipt record' },
      remove: 'Remove',
      required: 'Add at least one payment proof or receipt record.',
      unsupported: 'Use a PDF, JPG, PNG, or WebP file.',
      tooLarge: 'The file is larger than 20 MB.',
    },
    actions: { save: 'Save donation', saving: 'Saving…', another: 'Record another donation', home: 'Go to home' },
    submissionErrors: {
      authentication: 'Refresh the session with your authorized email.',
      evidence_required: 'Add at least one payment proof or receipt record.',
      evidence_validation: 'Review the file format and size.',
      evidence_upload: 'The files remain available. Try saving again.',
      record: 'The draft and files remain available. Try saving again.',
      default: 'The record remains available as a draft. Try saving again.',
    },
    success: {
      eyebrow: 'Record confirmed',
      title: 'The monetary donation was saved.',
      copy: 'The reference links the donor, amounts, applied rate, and evidence.',
      reference: 'Donation reference',
      note: 'The local draft closed after Supabase confirmed persistence.',
    },
    auth: sharedAuth.en,
  },
}

