export const chartCopy = {
  es: {
    heading: 'COMPORTAMIENTO',
    trend: 'Evolución de los resultados',
    columns: 'Resultados por período',
    timeline: 'Resultados registrados',
    stat: 'Resultado registrado',
    status: 'Estado de cumplimiento',
    empty: 'Todavía no hay resultados cargados para dibujar el comportamiento.',
    tooFewForTrend: 'Con menos de tres resultados se muestran columnas: dos puntos aún no describen una tendencia.',
    drafts: (count) => `Se excluyeron ${count} ${count === 1 ? 'resultado en borrador' : 'resultados en borrador'} del gráfico.`,
    viewData: 'Ver datos',
    period: 'Período',
    value: 'Resultado',
    cumulative: 'Acumulado',
    statusColumn: 'Estado',
    responsible: 'Responsable',
    target: 'Meta',
    average: 'Promedio',
    achieved: 'Cumplido',
    notAchieved: 'Sin cumplir',
    lastValue: 'Último resultado',
    execution: 'Ejecución',
    targetPassed: 'La meta se superó.',
    draft: 'Borrador',
    submitted: 'Incluido',
    verified: 'Verificado',
    summary: (name, value, target) => target ? `${name}. Último resultado ${value}, meta ${target}.` : `${name}. Último resultado ${value}.`,
    displayAs: 'Cómo se ve este indicador',
    boardPreview: 'Así aparece en el tablero:',
    displayAsHelp: 'Edifica elige la forma según los datos registrados. Puedes fijar otra si prefieres.',
    automatic: (form) => form ? `Automático (recomendado): ${form.toLowerCase()}` : 'Automático (recomendado)',
    formNames: { gauge: 'Medidor circular', progress: 'Barra de avance', trend: 'Línea de evolución', columns: 'Columnas por período', stat: 'Solo el número', timeline: 'Línea de tiempo', status: 'Estado de cumplimiento' },
  },
  en: {
    heading: 'BEHAVIOR',
    trend: 'Result evolution',
    columns: 'Results per period',
    timeline: 'Recorded results',
    stat: 'Recorded result',
    status: 'Completion state',
    empty: 'No results have been recorded yet, so there is nothing to plot.',
    tooFewForTrend: 'Fewer than three results are shown as columns: two points do not describe a trend.',
    drafts: (count) => `${count} draft ${count === 1 ? 'result was' : 'results were'} excluded from the chart.`,
    viewData: 'View data',
    period: 'Period',
    value: 'Result',
    cumulative: 'Cumulative',
    statusColumn: 'Status',
    responsible: 'Responsible',
    target: 'Target',
    average: 'Average',
    achieved: 'Achieved',
    notAchieved: 'Not achieved',
    lastValue: 'Latest result',
    execution: 'Execution',
    targetPassed: 'The target was exceeded.',
    draft: 'Draft',
    submitted: 'Included',
    verified: 'Verified',
    summary: (name, value, target) => target ? `${name}. Latest result ${value}, target ${target}.` : `${name}. Latest result ${value}.`,
    displayAs: 'How this indicator is displayed',
    boardPreview: 'This is how it appears on the board:',
    displayAsHelp: 'Edifica picks the form from the recorded data. You can set a different one.',
    automatic: (form) => form ? `Automatic (recommended): ${form.toLowerCase()}` : 'Automatic (recommended)',
    formNames: { gauge: 'Radial gauge', progress: 'Progress meter', trend: 'Trend line', columns: 'Columns per period', stat: 'Number only', timeline: 'Timeline', status: 'Completion state' },
  },
}
