export const chartCopy = {
  es: {
    heading: 'COMPORTAMIENTO',
    trend: 'Evolución de los resultados',
    columns: 'Resultados por período',
    timeline: 'Resultados registrados',
    stat: 'Resultado registrado',
    status: 'Estado de cumplimiento',
    empty: 'Todavía no hay resultados cargados para dibujar el comportamiento.',
    tooFewForTrend: 'Con menos de tres resultados se muestran columnas: dos puntos aún no describen una tendencia.',
    drafts: (count) => `Se excluyeron ${count} ${count === 1 ? 'resultado en borrador' : 'resultados en borrador'} del gráfico.`,
    viewData: 'Ver datos',
    period: 'Período',
    value: 'Resultado',
    cumulative: 'Acumulado',
    statusColumn: 'Estado',
    responsible: 'Responsable',
    target: 'Meta',
    average: 'Promedio',
    achieved: 'Cumplido',
    notAchieved: 'Sin cumplir',
    lastValue: 'Último resultado',
    execution: 'Ejecución',
    targetPassed: 'La meta se superó.',
    draft: 'Borrador',
    submitted: 'Incluido',
    verified: 'Verificado',
    summary: (name, value, target) => target ? `${name}. Último resultado ${value}, meta ${target}.` : `${name}. Último resultado ${value}.`,
  },
  en: {
    heading: 'BEHAVIOR',
    trend: 'Result evolution',
    columns: 'Results per period',
    timeline: 'Recorded results',
    stat: 'Recorded result',
    status: 'Completion state',
    empty: 'No results have been recorded yet, so there is nothing to plot.',
    tooFewForTrend: 'Fewer than three results are shown as columns: two points do not describe a trend.',
    drafts: (count) => `${count} draft ${count === 1 ? 'result was' : 'results were'} excluded from the chart.`,
    viewData: 'View data',
    period: 'Period',
    value: 'Result',
    cumulative: 'Cumulative',
    statusColumn: 'Status',
    responsible: 'Responsible',
    target: 'Target',
    average: 'Average',
    achieved: 'Achieved',
    notAchieved: 'Not achieved',
    lastValue: 'Latest result',
    execution: 'Execution',
    targetPassed: 'The target was exceeded.',
    draft: 'Draft',
    submitted: 'Included',
    verified: 'Verified',
    summary: (name, value, target) => target ? `${name}. Latest result ${value}, target ${target}.` : `${name}. Latest result ${value}.`,
  },
}
